Enable working Spark 2 clustering
crim-ca/patchwork pull request #6
Opened 2017-07-27 18:43 UTC by Mignastor

This enables working clustering on spark 2 because of the removal of spark logging.

2017-08-01 02:58 UTC, martinsotir requested changes
@Mignastor  Nice to see Patchwork officially updated to spark 2.1 !

I got the demo working on a small test cluster (Google Dataproc is awesome !).

However, it was not straightforward: I had to perform several edits in scala and bash scripts (see attached comments).

Also, this may be a matter of hyper parameter tunning, but Patchwork did not find any cluster on the demo dataset:

```
-----------------------------------------
number of points : 399
number of clusters : 0
-----------------------------------------
-----------------------------------------
size of epsilon : [0.2,0.2]
min pts in each cell : 1
time of training : 5305 ms
-----------------------------------------
```

@Mignastor Do you-know how we could fix this ?  ☺️

2017-08-01 02:58 UTC, martinsotir commented on runPatchwork.sh
> +spark2-submit --class PatchWorkDemo --master local[4] bin/patchwork_1.1.jar
The `spark2-submit` symlink is specific to Cloudera CDH (when spark 2.x is installed alongside spark 1.6),
I recommend keeping the more standard `spark-submit`.

Alternatively, we could check if `spark2-submit` exists and fallback to `spark-submit` ?

2017-08-01 02:58 UTC, martinsotir commented on build.sbt
> +  "org.apache.spark"  %% "spark-mllib"             % sparkVersion,
`spark-mllib` dependency included twice

2017-08-01 02:58 UTC, martinsotir commented on build.sbt
>  scalariformSettings
I am getting errors when compiling the project (`sbt compile`):

```
[info] Resolving org.apache#apache;14 ...
[error] Server access Error: Connection timed out (Connection timed out) url=http://repo.akka.io/releases/org/apache/spark/spark-parent_2.11/2.1.0/spark-parent_2.11-2.1.0.jar
[info] Resolving org.apache#apache;10 ...
[error] Server access Error: Connection timed out (Connection timed out) url=http://repo.akka.io/releases/org/apache/apache/10/apache-10.jar
```

This is fixed by removing the line 18 below : `resolvers += "Akka Repository" at "http://repo.akka.io/releases/"`. 
It appears that no akka.io dependencies is used anyway.

2017-08-01 02:58 UTC, martinsotir commented on runPatchwork.sh
> +spark2-submit --class PatchWorkDemo --master local[4] bin/patchwork_1.1.jar
Option `--master local[4]` has no effect here, it seems that the spark master is overridden in [PatchWorkDemo.scala, line 18](https://github.com/crim-ca/patchwork/blob/MAJ-spark-2/src/main/scala/example/PatchWorkDemo.scala#L18) : 

The `.setMaster("local[4]")` prevents us from changing the spark master without re-compiling the code.
This can be very confusing. We should remove this line.

2017-08-01 02:58 UTC, martinsotir commented on runPatchwork.sh
> +spark2-submit --class PatchWorkDemo --master local[4] bin/patchwork_1.1.jar
The [`/bin` directory](https://github.com/crim-ca/patchwork/tree/MAJ-spark-2/bin) needs to be updated.
@Mignastor Could-you add a precompiled jar of the version 1.1 (and remove the 1.0 jar) ?

2017-08-01 02:58 UTC, martinsotir commented on runPatchwork.sh
> +spark2-submit --class PatchWorkDemo --master local[4] bin/patchwork_1.1.jar
To ease reproducility we should provide the `Compound.csv` dataset, required in the demo.

I suggest we:

1. [ ] use an explicit and absolute HDFS path in [PatchWorkDemo.scala, line 23](https://github.com/crim-ca/patchwork/blob/MAJ-spark-2/src/main/scala/example/PatchWorkDemo.scala#L23) : `sc.textFile("hdfs:/datasets/Compound.csv")`

2. [ ] add commands to download and upload the sample dataset to HDFS in ` runPatchwork.sh`. The following worked for me:
  ```bash
  curl http://cs.joensuu.fi/sipu/datasets/Compound.txt | tr "\\t" "," > Compound.csv
  hdfs dfs -mkdir -p /datasets && hdfs dfs -put Compound.csv /datasets/
  ```

2017-08-02 01:12 UTC, martinsotir commented
Thanks for the update @Mignastor. 
I think two issues remain before merging:

- [ ] Remove `.setMaster("local[4]")` in PatchWorkDemo.scala, line 18
- [ ] Describe how to download the dataset required for the demo. For instance add `curl http://cs.joensuu.fi/sipu/datasets/Compound.txt | tr "\\t" "," > Compound.csv` in runPatchwork.sh (or directly provide the dataset in the repository with the appropriate copyright notice).

2017-08-02 17:39 UTC, Mignastor commented
@martinsotir thanks for your review!
I made some changes based on your comments, have a look.

2017-08-02 18:33 UTC, martinsotir commented
Works smoothly on my cluster:

```
-----------------------------------------
number of points : 7826
number of clusters : 4
-----------------------------------------
   cluster 2 has 430 cells
   cluster 4 has 492 cells
   cluster 18 has 219 cells
   cluster 28 has 30 cells
-----------------------------------------
size of epsilon : [0.4,0.4]
min pts in each cell : 1
time of training : 2990 ms
-----------------------------------------
```

PR accepted !

2017-08-02 18:34 UTC, martinsotir approved these changes

2017-08-02 18:38 UTC, merged